// <auto-generated />
using System;
using BeaconMap.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeaconMap.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("BeaconMap.Api.Domain.CoordinationPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DisasterId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Location")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisasterId");

                    b.ToTable("CoordinationPoints");
                });

            modelBuilder.Entity("BeaconMap.Api.Domain.Disaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Area")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Disasters");
                });

            modelBuilder.Entity("BeaconMap.Api.Domain.Hazard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DisasterId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Location")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisasterId");

                    b.ToTable("Hazards");
                });

            modelBuilder.Entity("BeaconMap.Api.Domain.CoordinationPoint", b =>
                {
                    b.HasOne("BeaconMap.Api.Domain.Disaster", null)
                        .WithMany("CoordinationPoints")
                        .HasForeignKey("DisasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeaconMap.Api.Domain.Hazard", b =>
                {
                    b.HasOne("BeaconMap.Api.Domain.Disaster", null)
                        .WithMany("Hazards")
                        .HasForeignKey("DisasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeaconMap.Api.Domain.Disaster", b =>
                {
                    b.Navigation("CoordinationPoints");

                    b.Navigation("Hazards");
                });
#pragma warning restore 612, 618
        }
    }
}
